:linkattrs:

= Overview

The configuration and code changes that are done to spring boot based _Api Gateway_ application when deploying on to https://istio.io/[Istio] configured
environment.

NOTE: This application works only on Kubernetes Cluster as OpenShift does not yet support Istio

== Pre-requisites

* https://istio.io/[Istio] is configured and running in your environment
* istioctl binary is available in local path where build will be executed

== What becomes deprecated ?

When deploying with Istio we might not need the explicit tracing related
code to be added in the application business logic, the code just need to propogate
the headers listed below as part of each request.  The Istio will take care of sending the
spans/traces associated with the headers to Zipkin

[NOTE]
====
Refer to the commented code in *CamelConfiguration* and *CamelServiceRoutes* for changes related to header propagation
====

== What you need ?

=== Tracing

As mentioned in previous sections the following are the headers that needs to be propagated with
each request that needs to be traced:

- x-request-id
- x-b3-traceid
- x-b3-spanid
- x-b3-parentspanid
- x-b3-sampled
- x-b3-flags
- x-ot-span-context

=== Circuit Breakers

_*WIP*_


[build-and-deploy]]
==  Building and Deploying

[[build]]
=== Build
[code,sh]
----
./mvnw clean install
----

[[deploy]]
=== Deploy

The build above should create the required kubernetes manifests that allows to deploy the service in Istio Service Mesh.
All the files will be located in the *target* directory of the project

[code,sh]
----

kubectl apply -f target/istio/istio-api-gateway.yaml <1>

----

<1> Deploy the api-gateway in to kubernetes cluster and create the _api-gateway_ service

== References

- https://istio.io/[Istio]
- https://istio.io/docs/tasks/integrating-services-into-istio.html[Integrating to Service Mesh]
- https://istio.io/docs/tasks/zipkin-tracing.html[Distributed Tracing with Istio]





