##################################################################################################
#  Api Gateway
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: istio-api-gateway
  labels:
    app: istio-api-gateway
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: istio-api-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-api-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-api-gateway
        version: "0.0.1"
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        - name: AB_OFF
          value: ""
        name:  spring-boot
        image: istio-api-gateway:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
